# Generated by Django 3.1.6 on 2021-02-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210208_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(choices=[(8, '8'), (16, '16'), (32, '32'), (64, '64'), (128, '128'), (200, '200')], default=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
