# Generated by Django 3.1.6 on 2021-02-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210209_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('site', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('pw', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='StorePass',
        ),
    ]
