# Generated by Django 3.1.6 on 2021-02-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210210_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Store',
        ),
    ]
