# Generated by Django 3.1.6 on 2021-02-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210210_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Vault',
        ),
    ]
